[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
palm_presale = "49rddQiFfKpfmDRfwrm7ySpSDjderN96rbrjcrgu1wrP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
